version: '3.8'
services:
  api:
    build: ./
    depends_on:
      - db
    container_name: api_server
    ports:
      - 8080:8080
    environment:
      - UPDATE_SRV_DB_CONNECTION_STRING_TEST=postgresql+asyncpg://${POSTGRES_USER_TEST}:${POSTGRES_PASSWORD_TEST}@${POSTGRES_HOST_TEST}:${POSTGRES_PORT_TEST}/${POSTGRES_DB_TEST}
      - UPDATE_SRV_DB_CONNECTION_STRING=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - SECRETJWT=${SECRETJWT}
      - ALGORITHMJWT=${ALGORITHMJWT}
  db:
    image: postgres:14.2
    restart: always
    container_name: db_server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p 5432
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
